name: Build and Appliction
run-nme: Build and test workflow

on:
    push:
    pull_request:
      types:
        - opened
        - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
        name: Checkout project
      - uses: actions/setup-java2v3
        name: Setup Java
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run test and builddind
        run: ./mvnw clean test compile war:war
